const { JWT } = require('google-auth-library');
const GoogleSpreadsheet = require('google-spreadsheet');

const testFn = async () => {
	// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
	const serviceAccountAuth = new JWT({
		// env var values here are copied from service account credentials generated by google
		// see "Authentication" section in docs for more info
		email: google.client_email,
		key: google.private_key,
		scopes: [
			'https://www.googleapis.com/auth/spreadsheets',
		],
	});
	try {
		const doc = new GoogleSpreadsheet.GoogleSpreadsheet('19VPbIPuhK2ZJW0HKPqbqCNKueSVUDBxxzoclH6d7_PM', serviceAccountAuth);

		await doc.loadInfo(); // loads document properties and worksheets
		console.log(doc.title);
		// await doc.updateProperties({ title: 'renamed doc' });

		// const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
		// console.log(sheet.title);
		// console.log(sheet.rowCount);
	} catch (error) {
		console.log(error.config.data)
	}
}

testFn();